Solar-network/core

packages/core-cli/src/services/installer.ts
packages/core-cli/src/services/updater.ts
packages/core/src/cli.ts
packages/core/src/commands/config-cli.ts
packages/core/src/commands/reinstall.ts

Updates the cli to use git instead of npm.
Also removed the restriction that limited checking for updates to once per day and now it only checks when the specific `update` command is executed (instead of every time the cli is run) to save resources.

refactor(core-cli): use git instead of npm for reinstall and update

---

packages/core-api/src/controllers/blockchain.ts
packages/core-api/src/services/delegate-search-service.ts
packages/core-kernel/src/utils/delegate-calculator.ts
packages/core-kernel/src/utils/supply-calculator.ts

The existing implementation of the supply calculator computes the supply by adding the inital supply to the static forging reward value multiplied by the height. This was not enough with the introduction of a burn transaction and dynamic rewards. The function has been rewritten to actually sum all the non-negative wallet balances (including locked htlc tokens) so that it will correctly return the current supply.

fix: supply calculator

---

packages/core-p2p/src/socket-server/plugins/version.ts
packages/core-p2p/src/socket-server/server.ts

The `/api/peers` endpoint previously only showed the version of Core that the peer was running when it was first added to our peer repository via the `version` property of each peer object. This meant that when a peer updated their version of Core, if they restarted and reconnected before we forgot the peer, we would still see their old version on the endpoint and it would be very slow to update to reflect the true version of Core each peer is running.
This adds a new plugin to the socket server to update the `version` property of each peer whenever they communicate with us, since most incoming messages include their version in the message header. This means `/api/peers` now updates instantly with the correct version when a peer updates (or theoretically downgrades) their version of Core.

feat(core-p2p): faster update of peers endpoint with peer version

---

packages/core-p2p/src/peer-processor.ts

The `ports` object of a newly added peer is always empty until Core decides to ping the new peer's ports at a point in time in the future. This can lead to inconsistent results and unexpected behaviour if a peer requires a plugin or service's port to always be discoverable.
This changes that behaviour so Core immediately pings the ports of a new peer, so the `ports` object will always contain the expected data from the moment the peer is accepted.

feat(core-p2p): faster port discovery for new peers

---

packages/core-api/src/schemas.ts
packages/core-snapshots/src/verifier.ts
packages/core-test-framework/src/app/generators/crypto.ts
packages/core/src/commands/network-generate.ts
packages/crypto/src/blocks/block.ts
packages/crypto/src/blocks/deserializer.ts
packages/crypto/src/blocks/factory.ts
packages/crypto/src/crypto/hash.ts
packages/crypto/src/crypto/message.ts
packages/crypto/src/networks/devnet/genesisBlock.json
packages/crypto/src/networks/devnet/milestones.json
packages/crypto/src/networks/devnet/network.json
packages/crypto/src/networks/testnet/genesisBlock.json
packages/crypto/src/networks/testnet/network.json
packages/crypto/src/transactions/deserializer.ts
packages/crypto/src/transactions/signer.ts
packages/crypto/src/transactions/types/schemas.ts
packages/crypto/src/transactions/verifier.ts
packages/crypto/src/validation/schemas.ts

ECDSA signatures can be malleable and there have been multiple public disclosures of ECDSA-related security vulnerabilities affecting the upstream code in the past. Although all known malleability issues have been patched upstream as of the time of this PR, it cannot be guaranteed that there will be no more future issues regarding ECDSA malleability in the future due to the nature of how ECDSA and ASN.1 work. Despite these risks, blocks in Core are still exclusively signed using ECDSA, and transactions can be either Schnorr or ECDSA.
Since this is a new blockchain with no baggage, this PR removes support for ECDSA, forcing blocks and transactions to be exclusively signed using Schnorr, which does not suffer from the same malleability issues as ECDSA.
As a consequence of this change, new …

refactor(crypto): use schnorr for block signatures and remove legacy ecdsa support

---

packages/core-forger/src/actions/forge-new-block.ts
packages/core-forger/src/client.ts
packages/core-forger/src/forger-service.ts
packages/core-kernel/src/contracts/p2p/network-monitor.ts
packages/core-kernel/src/contracts/p2p/server.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/socket-server/controllers/internal.ts
packages/core-p2p/src/utils/build-rate-limiter.ts
packages/core/bin/config/devnet/app.json
packages/core/bin/config/mainnet/app.json
packages/core/bin/config/testnet/app.json

The upstream code only attempts to forge a new block once, at the start of the slot. If, due to network latency or other factors, the node didn't receive the previous block by this time, it will fail to forge due to insufficient quorum and it will miss a block. This means even if the node regains sync during the slot, it will still miss. Since a slot lasts for 8 seconds, there is a lot of wasted opportunity by not trying again to forge throughout this time window.
This PR changes this behaviour so the forger will retry forging if it fails. It will attempt to forge once per second, until our forging slot is over or until it succeeds and the block is accepted by our node.
Some of the code may seem redundant, such as `currentSlot`, `lastBlockSlot` and `state` being set multiple times with …

refactor: retry forging throughout slot

---

packages/core-forger/src/forger-service.ts
packages/core-kernel/src/contracts/p2p/network-state.ts
packages/core-p2p/src/network-state.ts

The upstream code logs if it thinks there is attempted double forgery from our delegate via overheight block headers (i.e. if there is already a block at a higher height than our node which is purportedly from our delegate), but Core does not stop us from forging anyway in that situation, which risks forking the network. This is due to lack of cryptographic verification of the potentially double forged block, so it errs on the side of caution to prevent a bad actor halting the network by spamming each delegate with cryptographically unverified block headers at a higher height but with the delegate's own public key when they are due to forge.
Now we actually cryptographically verify the signature of the block header to definitively identify if the overheight block header is legitimately …

refactor: limited double forgery mitigation

---

packages/core-forger/src/forger-service.ts
packages/core-kernel/src/contracts/p2p/network-state.ts
packages/core-kernel/src/contracts/p2p/peer-communicator.ts
packages/core-kernel/src/contracts/p2p/peer.ts
packages/core-kernel/src/utils/index.ts
packages/core-kernel/src/utils/is-forger-running.ts
packages/core-kernel/src/utils/stringify.ts
packages/core-p2p/src/enums.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/network-state.ts
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/peer.ts
packages/core-p2p/src/schemas.ts
packages/core-p2p/src/socket-server/codecs/peer.ts
packages/core-p2p/src/socket-server/codecs/proto/peer.proto
packages/core-p2p/src/socket-server/codecs/proto/protos.d.ts
packages/core-p2p/src/socket-server/codecs/proto/protos.js
packages/core-p2p/src/socket-server/controllers/peer.ts

Core calculates network quorum (used for consensus) and general network health (used for determining rollbacks) by analysing the state of the entire network; that is, all nodes, whether they are active delegates, inactive delegates, former delegates or just relays.
This PR revises that behaviour to only consider the responses of active delegates in most of these cases in order to ensure that only active delegates elected to control the network can influence these important calculations which can have significant impacts on the network going forward. In the case of network quorum, only the responses of active delegates are considered. In the case of analysing network health for determining rollbacks, we will accept state data from active delegates or other relays, but in the latter case, …

refactor(core-p2p): only use active delegates in calculations

---

packages/core-state/src/block-state.ts

This introduces a milestone-configurable option to burn a percentage of all transaction fees forged in a block.
So, for example, to burn 90% of all transaction fees per block (the delegates keep the remaining 10%), set `burnPercentage` to `90` in `milestones.json`. Valid values are integers between 0-100 inclusive.
For clarification, this only affects transaction fees and not the block reward itself.

feat(core-state): burn a percentage of all fees

---

packages/core-cli/src/commands/command.ts
packages/core-cli/src/input/parser.ts
packages/core/src/cli.ts
packages/core/src/commands/help.ts

For some inexplicable reason, setting the verbose flag `-v` in the CLI does nothing, and keeps logging at a normal level. To enable verbose mode, it requires `-vv`, and for debug logging, `-vvv`. This makes `-v` entirely redundant, so we change this so `-v` enables verbose mode and `-vv` enables debug mode.
In addition, in the case of certain errors and prompts, the CLI prints the same error or asks the same prompt twice. This annoying behaviour has been refactored away to remove this repetition.

fix(core-cli): stop repeating messages and change verbosity

---

.eslintrc.json
package.json
packages/core-cli/package.json
packages/core-cli/src/components/spinner.ts
packages/core-cli/src/services/installer.ts
packages/core-cli/src/services/updater.ts
packages/core/src/commands/config-cli.ts
packages/core/src/commands/reinstall.ts

This PR gives users more information during the reinstallation and update process of Core.
Previously, there would be one message printed at the start of the process, then nothing until the end. This meant the user was not aware of its progress and could think it had crashed.
This PR adds extra logging to keep the user informed throughout the process. Here is an example of how the logging looks during an update now:
```
✔ Update available 3.1.1-next.3  →  3.1.1-next.4. Would you like to update? … yes
✔ Downloading Core 3.1.1-next.4
❯ Preparing to build Core 3.1.1-next.4
✔ Fetching dependencies
✔ Linking dependencies
⠦ Building dependencies (3 of 18: bcrypto)
Building Core 3.1.1-next.4
```
This PR also introduces an alternative logging method when running in verbose mode. In that mode, …

feat(core-cli): more informative update and reinstall

---

packages/core-cli/src/services/plugin-manager.ts
packages/core-cli/src/services/source-providers/abstract-source.ts
packages/core-cli/src/services/source-providers/git.ts

The CLI does not output anything during a `plugin:install`, `plugin:update` or `plugin:remove` operation unless it throws an error.
This has been a source of confusion for several users when installing plugins, so this PR adds basic output to at least tell the user that an operation is in progress, and also prints a message when it has finished.
It now also prints the raw logs from `yarn` and `git` if the command is executed in verbose mode.

refactor(core-cli): print outcome of plugin manager action

---

packages/core-blockchain/src/blockchain.ts
packages/core-blockchain/src/state-machine/actions/check-later.ts
packages/core-kernel/src/contracts/blockchain/blockchain.ts
packages/core-kernel/src/contracts/p2p/network-monitor.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/peer-communicator.ts
packages/crypto/src/interfaces/block.ts

Core has an issue where we might not receive blocks in real time for one minute after starting. This happens because although our node syncs on startup by downloading blocks to catch up, another block is sent after that period which we don't catch. And since we don't have that block, we can't receive the subsequent ones either because they are not chained. This means we end up waiting 60 seconds for the wakeup routine to download those blocks before we finally start receiving blocks properly.
Now we automatically keep polling peers for the blocks that we don't have after syncing, so we should start receiving blocks in real time straight away. The polling stops when we eventually receive a block by the normal method.

refactor(core-blockchain): keep downloading until new block received

---

packages/core-kernel/src/contracts/shared/dynamic-fee.ts
packages/core-transaction-pool/src/dynamic-fee-matcher.ts
packages/core-transactions/src/errors.ts
packages/core-transactions/src/handlers/transaction.ts
packages/core-transactions/src/handlers/two/delegate-resignation.ts
packages/core-transactions/src/handlers/two/htlc-refund.ts
packages/crypto/src/transactions/types/schemas.ts
plugins/sxp-swap/src/sxp-swap.ts

In the previous implementation, dynamic fees were not enforced by consensus and a single delegate could lower the fees as far as 0.00000001 and the network would have accepted it. 
This PR incorporates fees into consensus. More specifically, fees cannot be lowered under a certain threshold calculated with the same formula used for dynamic fees.
This was introduced to avoid delegates lowering fees for themselves or others to avoid/reduce the amount of burned fees.

feat: fees by consensus

---

packages/core-api/src/controllers/blockchain.ts
packages/core-database/src/repositories/transaction-repository.ts

This adds a new `burned` object to the `/api/blockchain` endpoint to see the total amount of transaction `fees` that were burned, as well as the total amount burned via the custom burn `transactions` type, and the combined `total` of both.

feat(core-api): add burned totals to /api/blockchain endpoint

---

packages/core-cli/src/services/source-providers/abstract-source.ts
packages/core-cli/src/services/source-providers/git.ts

Now that we have moved all the packages to our own scope, any existing third party plugins that depend on the upstream scope will no longer work.
Since we cannot, and should not, expect existing plugins for the upstream Core to be rewritten to target our own scope, this PR introduces a translation routine to automatically modify the plugin's source code to rewrite references to the upstream scope so that they are changed to use our scope whenever a plugin is installed or updated.

feat(core-cli): translate plugin package scope

---

packages/core-p2p/src/defaults.ts
packages/core-p2p/src/peer-communicator.ts

This PR comprises of two parts, both of which improve the responsiveness of peering with other delegates, which is now essential for calculating quorum to forge.
Firstly, we stop verifying signatures from the signed `p2p.peer.getStatus` endpoint as soon as we hit an invalid one, as it means a malicious actor is trying to do something nasty. By cutting the cord immediately, we don't waste processor time trying to verify more signatures from a peer that is obviously bad. An invalid signature is one that is either cryptographically incorrect, or from a public key that does not correspond to a currently active forging delegate.
Secondly, we disable the /24 subnet limit by default. This was originally set in the upstream code to prevent too many malicious relays overwhelming the network from …

refactor(core-p2p): delegate peering improvements

---

packages/core-forger/src/client.ts
packages/core-forger/src/forger-service.ts
packages/core-p2p/src/socket-server/codecs/internal.ts
packages/core-p2p/src/socket-server/controllers/internal.ts
packages/core-p2p/src/socket-server/routes/internal.ts
packages/core/bin/config/devnet/app.json
packages/core/bin/config/mainnet/app.json
packages/core/bin/config/testnet/app.json

Recent PR #11 temporarily reintroduced `core-database` as a dependency for the forger process due to the database requirement of `getBlockTimeLookup` which is used to get the current slot number.
It was always the intention that this would be temporary and this PR now refactors it to delegate the `getBlockTimeLookup` call to the connected relay, accessed via a new private `p2p.internal.getCurrentSlot` endpoint. This means the forger process is once again decoupled from the database, potentially allowing a forger to operate via a remote connection to a relay without the need for a local blockchain database on the same node as the forger.

refactor(core-forger): remove core-database dependency

---

packages/core-forger/src/client.ts
packages/core-forger/src/forger-service.ts
packages/core-kernel/src/contracts/p2p/network-state.ts
packages/core-kernel/src/contracts/p2p/server.ts
packages/core-p2p/src/network-state.ts
packages/core-p2p/src/socket-server/controllers/internal.ts

We know that the quorum-based consensus algorithm has flaws regarding double forgery. Sometimes it happens by accident, e.g. leaving a backup node forging after performing maintenance on their main node.
This PR improves the detection mechanism to catch more instances of accidental double forgery. However, it will not catch all cases - that is impossible - but, since we know the consequences, anything that improves the chance of reducing accidental double forgery on the network is worthwhile.
This issue will be resolved once and for all when we implement the new replacement consensus which does not use quorum.

refactor(core-forger): catch more cases of accidental double forgery

---

packages/core-api/src/resources-new/block.ts
packages/core-api/src/resources-new/transaction.ts
packages/core-api/src/routes/blocks.ts
packages/core-api/src/routes/delegates.ts
packages/core-api/src/routes/transactions.ts
packages/core-api/src/routes/votes.ts
packages/core-api/src/routes/wallets.ts
packages/core-api/src/schemas.ts

This resolves [an issue in the upstream code](https://github.com/ArkEcosystem/core/issues/4621) which remains open and unfixed at the time of this PR.
The bug causes a HTTP 500 Internal Server Error on the Public API and node log spam whenever somebody tries to access any of the following endpoints with an invalid `orderBy` query parameter:
`/api/blocks`
`/api/blocks/{id}/transactions`
`/api/delegates/{id}/blocks`
`/api/transactions`
`/api/votes`
`/api/wallets/{id}/transactions`
`/api/wallets/{id}/transactions/sent`
`/api/wallets/{id}/transactions/received`
`/api/wallets/{id}/votes`
Since a lengthy stack trace is printed in the node logs each time, we have taken the decision to fix it in our own codebase rather than waiting for upstream to resolve it as we have decided that this could …

fix(core-api): create block and transaction sorting schemas

---

packages/core-blockchain/src/state-machine/actions/check-last-downloaded-block-synced.ts
packages/core-blockchain/src/state-machine/actions/check-later.ts

As we get closer to launching the mainnet, we will see delegates, exchanges and ordinary users start to set up nodes in advance. Since no blocks will be coming in prior to the launch, the logs will get a bit messy as Core will try downloading non-existent blocks from other peers and it might look like something is wrong when it isn't. This PR tidies it up by immediately setting the state machine to `SYNCED` if the current time is earlier than the epoch time and then delays the polling for blocks function until the epoch time has been reached.
Oh, and it also adds a cute countdown timer ticking the days, hours, minutes and seconds in the log until launch. :)

feat(core-blockchain): countdown to mainnet launch

---

packages/core-blockchain/src/state-machine/actions/check-later.ts
packages/core-kernel/src/utils/format-seconds.ts
packages/core-kernel/src/utils/index.ts

This extracts the code to convert seconds to a pretty textual representation of days, hours, minutes and seconds into its own utility function, so it can be reused elsewhere in Core too.

feat(core-kernel): add format seconds function

---

packages/crypto/src/transactions/builders/transactions/ipfs.ts
packages/crypto/src/transactions/types/schemas.ts
packages/crypto/src/transactions/types/two/ipfs.ts

Solar Core's development team is actively engaged with the community in Discord and Telegram, and we listen to our valued members. We recently received a request from a community member to add vendorfield support to the IPFS transaction type so that users can optionally store up to 255 characters of free-form additional data with the hash, such as basic metadata or a description of what the IPFS hash is, or indeed, another IPFS hash associated with the transaction. There are multiple use cases where additional data is required alongside the hash, so this PR implements that request.

feat(crypto): add vendorfield to ipfs transaction type

---

packages/core-p2p/src/defaults.ts
packages/core-p2p/src/hapi-nes/plugin.ts
packages/core-p2p/src/hapi-nes/socket.ts
packages/core-p2p/src/service-provider.ts
packages/core-p2p/src/socket-server/plugins/ban-hammer.ts
packages/core-p2p/src/socket-server/server.ts

The upstream codebase relies on kernel-based iptables firewall rules to implement IP banning for denial of service mitigation. This is not portable as it requires superuser privileges and is tied to Linux kernels that include the netfilter module. Also, it is optional and requires manual activation at the end, their rules have been known to conflict with existing firewall rules and [there was recently a security vulnerability discovered inside the very tool the upstream Core uses to protect itself](https://www.zdnet.com/article/nasty-linux-netfilter-firewall-security-hole-found/). There have also already been several denial of service security exploits that were not prevented by iptables rules, rendering it not fit for this particular purpose.
With all these facts combined, it was decided …

feat(core-p2p): peer banning mechanism

---

packages/core-transaction-pool/src/defaults.ts

There is a bug in the upstream implementation of the transaction pool as it places its sqlite storage files in the wrong location. This prevents the `pool:clear` CLI option from ever working.
This PR moves the storage files to the correct location, so now `solar pool:clear` works as expected.

fix(core-transaction-pool): set storage to correct directory

---

install.sh
packages/core-cli/src/services/installer.ts
packages/core-kernel/src/services/config/drivers/local.ts
packages/core/src/cli.ts

This PR revises the architecture of the Core installation to fix some issues.
The installer no longer relies on identifying English language strings in the logs so it should now work with non-English locales, and we no longer export any environment variables to the shell. Before, we were modifying things like `CPATH`, `CFLAGS`, `LDFLAGS` and so on which may have had adverse consequences if anyone tried building unrelated tools using a compiler under the user account running Core. Now, we only set up aliases for `solar` and `pm2` in the shell and leave the rest untouched. Those previously exported flags are instead located in a separate `.env` file inside `.solar/` and are used internally by the installer and by Core without affecting the shell.
This means Solar Core only modifies the …

refactor: keep deps and env vars inside .solar dir

---

packages/core/src/commands/uninstall.ts

The upstream code currently does not implement an uninstaller. There is an `uninstall` CLI command but it merely prints `This command has not been implemented` and aborts. That means in order to remove upstream's Core, you have to manually erase the Core directory and then scout around the disk to find other remnants scattered across various directories, manually drop the database and then try to delete Core's dependencies, hoping that it won't break anything else that might depend on them since they're installed globally.
In contrast, Solar Core installs everything locally and neatly within a defined directory structure with no global dependencies, so we can implement a proper uninstaller that cleanly removes all traces of Core. It stops the processes, removes the pm2 reboot cronjob, …

feat(core): implement uninstall command

---

packages/core/src/commands/pool-clear.ts
packages/core/src/commands/reinstall.ts

The `pool:clear` command was missing a `force` flag and the code was instead looking for a `false` flag which I presume was a typo.
The `reinstall` command checked the value of the `token` flag but it was not set in the command definition, so it was undefined by default unless explicitly set. This meant the command would fail unless a value for `token` was passed as a command line argument.
Both issues are present in the upstream Core and were not a result of any modifications by Solar.

fix(core-cli): correctly implement flags

---

packages/core/bin/run

[I originally implemented jemalloc as the memory allocator in the upstream Core back in 2020](https://github.com/ArkEcosystem/core/pull/3541) as a result of problems with memory fragmentation. In the end, it was [traced to a memory leak caused by the use of compression in the p2p middleware](https://github.com/ArkEcosystem/core/issues/2803).
[Since I fixed that memory leak](https://github.com/ArkEcosystem/core/pull/3518), and the entire p2p middleware was subsequently replaced in Core 3.x, there is no major need for jemalloc anymore, so we no longer ship it.

chore(core): remove jemalloc

---

packages/core-p2p/src/peer-communicator.ts

Peer discovery in the upstream wallet relies on the Public API port being exposed via `@arkecosystem/core-api`. Until now, we have been exposing our Public API exclusively as `@solar-network/core-api`. While this works with our own wallet, it breaks compatibility with the peer discovery mechanism in the upstream wallet.
Since some people may prefer to continue using the wallet provided by the upstream maintainers instead, this PR now exposes the Public API port via both `@arkecosystem/core-api` and `@solar-network/core-api`.

refactor(core-api): wallet compatibility

---

packages/core/bin/config/testnet/app.json
plugins/sxp-swap/src/defaults.ts
plugins/sxp-swap/src/sxp-swap.ts

Previous version of the swap plugin would not validate a swap in case one of the api nodes was not in sync and they would be the first to reply. This PR fixes this issue by not considering non valid responses from api.
This PR also includes changes of the plugin defaults in preparation for mainnet and the removal of the plugin from testnet.

chore: sxp-swap maintenance

---

install.sh
packages/core/src/commands/database-create.ts

This adds a new `database:create` command to the CLI to (re)create the necessary structure for a new PostgreSQL database for the specified network in our local architecture.
Accordingly, the install script has also been refactored to use this command as part of the setup routine.

feat(core): new command to create database

---

packages/core-state/src/block-state.ts
packages/core-transactions/src/handlers/one/vote.ts
packages/core-transactions/src/handlers/two/vote.ts
packages/crypto/src/transactions/types/one/vote.ts
packages/crypto/src/validation/schemas.ts

This PR updates the asset of the vote transaction type to accept a delegate name in place of the public key, e.g. `+gym` for a vote or `-gym` for an unvote. For backwards compatibility, the public key is still accepted.
This means the Ledger app can display the name of the delegate a user is about to vote or unvote, rather than only their public key, which significantly improves the user experience. The delegate name is short enough for a user to easily check and confirm it is correct on the Ledger screen, unlike the public key which is not usually displayed in the wallet anyway when voting and is 66 characters long, therefore making a user susceptible to skipping it and not actually verifying it properly.

feat: delegate name in vote asset

---

packages/core-database/src/model-converter.ts
packages/core-kernel/src/contracts/state/block-state.ts
packages/core-state/src/block-state.ts
packages/crypto/src/blocks/block.ts
packages/crypto/src/interfaces/transactions.ts
packages/crypto/src/transactions/deserializer.ts
packages/crypto/src/transactions/types/transaction.ts

This PR moves the fee burn calculation logic out of the deserialiser so that it has better compatibility with milestones.
The formula for calculating the fee burn has also been simplified. It is mostly functionally equivalent, with the exception that any  _de minimis_ decimal truncation is now favourable for the delegate that forged the transaction which previously was not the case. In other words, assuming we burn 90% of a 1.00000123 SXP fee, this would mathematically be 0.900001107, but the coin is limited to 8 decimal places so the final decimal is truncated. Previously 0.90000111 SXP would have been burned with the delegate keeping 0.10000012 SXP but with the revised formula, 0.90000110 SXP is burned so the delegate keeps 0.10000013. The difference is so negligible that it is …

refactor(crypto): use milestone height for transaction fee burn

---

install.sh
package.json
packages/core-api/package.json
packages/core-api/src/controllers/controller.ts
packages/core-api/src/controllers/node.ts
packages/core-api/src/plugins/pagination/ext.ts
packages/core-api/src/schemas.ts
packages/core-blockchain/package.json
packages/core-cli/package.json
packages/core-cli/src/components/warning.ts
packages/core-database/package.json
packages/core-database/src/service-provider.ts
packages/core-forger/package.json
packages/core-kernel/package.json
packages/core-logger-pino/package.json
packages/core-p2p/package.json
packages/core-snapshots/package.json
packages/core-state/package.json
packages/core-transaction-pool/package.json
packages/core-transactions/package.json
packages/core-webhooks/package.json
packages/core/package.json
packages/crypto/package.json
packages/crypto/src/networks/mainnet/milestones.json
packages/crypto/src/networks/mainnet/network.json
packages/crypto/src/networks/testnet/milestones.json
packages/crypto/src/networks/testnet/network.json
packages/utils/package.json
pnpm-lock.yaml

This PR releases Solar Core 3.2.2 for mainnet.
Changes since 3.2.1:
\- installation script no longer throws an error if cron is not installed
\- dynamic fees now shown in the correct section of `/api/node/configuration`
\- zero fee transaction types now included in the dynamic fees section of `/api/node/configuration`
\- static fee values added for better wallet compatibility and to prevent overspending on fees
\- network names for mainnet and testnet now set correctly in crypto package
\- postgresql database permissions now always reset on core startup in case of unclean shutdown
\- version bump of `moment` dependency due to a security vulnerability in that package
\- merged bug fix for empty `orderBy` query parameter in api pagination from upstream code
\- fixed bug when sorting …

release: mainnet 3.2.2

---

packages/core-api/src/controllers/blocks.ts

There is a bug in the upstream code for the Public API which means `/api/blocks/last` raises an Internal Server Error and dumps log spam if the last block in the blockchain contains any multipayments. It would also affect `/api/blocks/first` if the genesis block contained one or more multipayments.
This PR fixes the bug by calling the `show` method for `first` and `last` in the `BlocksController` so it now fetches the relevant block via the `blockHistoryService` instead of directly from the `blockchain` object. Another benefit of taking this approach is that now the blocks returned via `first` and `last` using `?transform=false` are the same structure as when fetching blocks by height or id. For example, the responses from `/api/blocks/first?transform=false` and …

fix(core-api): use blockHistoryService for first and last block retrieval

---

packages/core-api/src/plugins/pagination/ext.ts

Fixes the following bug in upstream Core: https://github.com/ArkEcosystem/core/issues/4647

fix(core-api): use dot notation in pagination result

---

packages/core-api/package.json
packages/core-api/src/plugins/pagination/ext.ts
packages/core-blockchain/package.json
packages/core-cli/package.json
packages/core-database/package.json
packages/core-forger/package.json
packages/core-kernel/package.json
packages/core-logger-pino/package.json
packages/core-p2p/package.json
packages/core-p2p/src/defaults.ts
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/peer-connector.ts
packages/core-p2p/src/service-provider.ts
packages/core-p2p/src/transaction-broadcaster.ts
packages/core-snapshots/package.json
packages/core-state/package.json
packages/core-transaction-pool/package.json
packages/core-transactions/package.json
packages/core-webhooks/package.json
packages/core/package.json
packages/crypto/package.json
packages/utils/package.json
pnpm-lock.yaml

This PR releases Solar Core 3.2.4 for mainnet.
Changes since 3.2.3:
\- fixed pagination bugs in `core-api` originally present in upstream code
\- connection timed out errors are no longer printed to reduce pollution in logs
\- `async` dependency updated from 2.6.3 to 2.6.4 to address a prototype pollution vulnerability
\- merged `core-api` changes from upstream code to use `qs` instead of `querystring`
\- transactions are now broadcast to all peers rather than only 20

release: mainnet 3.2.4

---

packages/core-snapshots/src/verifier.ts
packages/crypto/src/blocks/block.ts
packages/crypto/src/blocks/factory.ts
packages/crypto/src/crypto/hash.ts
packages/crypto/src/interfaces/transactions.ts
packages/crypto/src/transactions/builders/transactions/transaction.ts
packages/crypto/src/transactions/signer.ts
packages/crypto/src/transactions/types/schemas.ts
packages/crypto/src/transactions/verifier.ts
packages/crypto/src/utils/index.ts

The code we inherited from upstream uses a deprecated and potentially vulnerable version of Schnorr signatures originally used in Bitcoin Cash which the Bitcoin Core team found too problematic and never actually implemented.
This pull request introduces the necessary changes to add BIP340 Schnorr signatures to Solar's `crypto` library and deprecates the legacy Schnorr signatures. It will also require some changes to `core-transactions` and further generic refactoring of `crypto` which will follow in separate PRs.
Upon the activation of the new `bip340` milestone (height to be confirmed), all blocks and messages must immediately be signed using BIP340 Schnorr signatures. Legacy Schnorr signatures will be invalid for those as soon as the milestone is hit. The activation of the milestone …

feat(crypto): bip340 schnorr signatures

---

packages/core-api/src/resources-new/delegate.ts
packages/core-api/src/services/delegate-search-service.ts
packages/core-api/src/www/api.json
packages/core-kernel/src/contracts/state/wallets.ts
packages/core-state/src/dpos/dpos.ts
packages/core-transactions/src/handlers/one/delegate-registration.ts
packages/core-transactions/src/handlers/one/vote.ts
packages/core-transactions/src/handlers/two/delegate-registration.ts

Core's Public API lacks an easy way to see how many wallets are voting for each delegate without querying each delegate's endpoint individually. This PR improves on this by adding a `delegate.voters` attribute to all delegates, with the total number of wallets voting for that delegate. This information is now exposed via `/api/delegates` and `/api/delegates/{id}`.
This brings the same functionality as the [@dpos-info/core-voter-count](https://github.com/dpos-info/core-voter-count) plugin but natively in Core and we would like to recognise, acknowledge and thank them their reference implementation. Implementing it natively in Core also means new search and sorting criteria has been added to the `/api/delegates` API endpoint for the `voters` attribute and it will continue to work correctly …

feat: add delegate.voters attribute

---

packages/core-transactions/src/handlers/two/htlc-claim.ts
packages/crypto/src/crypto/hash-algorithms.ts
packages/crypto/src/enums.ts
packages/crypto/src/interfaces/transactions.ts
packages/crypto/src/transactions/types/schemas.ts
packages/crypto/src/transactions/types/two/htlc-claim.ts
packages/crypto/src/transactions/types/two/htlc-lock.ts

The default implementation of HTLC is restricted to SHA256 hashes only. This PR introduces additional support for SHA384, SHA512, SHA3-256, SHA3-384, SHA3-512, Keccak256, Keccak384 and Keccak512 too, with an easily extensible system to add additional hash algorithms to HTLC transactions in the future if necessary. It updates the schema for HTLC Lock and HTLC Claim transactions to allow hashes of 64, 96 and 128 characters and extends the HTLC Claim transaction type to specify a `hashType` in the `claim` asset, where the value is a numerical enum corresponding to the following:
```
SHA256 = 0,
SHA384 = 1,
SHA512 = 2,
SHA3256 = 3,
SHA3384 = 4,
SHA3512 = 5,
Keccak256 = 6,
Keccak384 = 7,
Keccak512 = 8
```
The `hashType` is optional and will default to SHA256 if omitted. The rationale is that …

feat: support more hash algorithms for htlc

---

packages/core-blockchain/src/blockchain.ts
packages/core-blockchain/src/state-machine/actions/check-later.ts
packages/core-kernel/src/contracts/blockchain/blockchain.ts
packages/core-p2p/src/socket-server/controllers/blocks.ts

Earlier enhancements to Solar Core have already made it flexible enough to stay in sync as a relay even when behind a firewall (i.e. when the P2P port is closed). However, it did not work if a forging node was behind a firewall. This PR makes it so forging nodes can also stay in sync behind a firewall or with the P2P port closed.
It is worth mentioning that this is primarily designed to maintain the health of the network to avoid missed blocks in the event that a forging node is not properly configured and is absolutely not intended to suggest that delegates should run their nodes with the P2P port closed due to the fact that such nodes will not receive transactions and there is a necessity that delegate nodes must be contactable by other delegate nodes in order to participate in …

refactor: keep downloading blocks while p2p port is closed

---

packages/crypto/src/transactions/types/schemas.ts
packages/crypto/src/validation/schemas.ts

The upstream code only allows vote transactions to use the public key in the asset. Since Solar's launch on mainnet, we have also allowed (and preferred) vote transactions with the username in the asset, since this is more compact (meaning fewer bytes per transaction, ergo a lower fee) and provides a better user experience for the upcoming Ledger app.
We kept support for voting via public key to maintain compatibility with the upstream wallet and tooling, however, enough time has passed now to finally drop support for the public key in the asset. This will come into effect with version 3 transactions, since the upstream wallet and tooling will not support them anyway.

refactor(crypto): disallow voting by public key in v3 transactions

---

packages/core-api/package.json
packages/core-blockchain/package.json
packages/core-cli/package.json
packages/core-database/package.json
packages/core-forger/package.json
packages/core-kernel/package.json
packages/core-logger-pino/package.json
packages/core-p2p/package.json
packages/core-snapshots/package.json
packages/core-state/package.json
packages/core-transaction-pool/package.json
packages/core-transactions/package.json
packages/core-transactions/src/handlers/two/multi-signature-registration.ts
packages/core-webhooks/package.json
packages/core/package.json
packages/crypto/package.json
packages/utils/package.json

This PR releases Solar Core 3.2.5 for mainnet.
Changes since 3.2.4:
\- disable multisignature registrations

release: mainnet 3.2.5

---

packages/core-blockchain/src/blockchain.ts
packages/core-blockchain/src/process-blocks-job.ts
packages/crypto/src/interfaces/block.ts

Earlier today there was a brief period of degraded service on mainnet due to a temporary fork resulting from a delegate broadcasting its block late since the processing phase took considerably longer than usual. Usually block processing takes a fraction of a second, but on this occasion it took a full 8 seconds, so the propagation entered the next delegate's forging slot. This meant some nodes received the late delegate's block and other nodes received the next delegate's block, both at the same height. The likely cause for this delay and fork was resource starvation on the late forging delegate's server.
While we are certain there was no malicious intent and this was an accident, it is nevertheless an issue that we should resolve to minimise the risk of a future reoccurrence. We …

refactor(core-blockchain): broadcast only if enough time left in slot

---

packages/core-transactions/src/errors.ts
packages/core-transactions/src/handlers/core/multi-payment.ts
packages/core-transactions/src/handlers/transaction.ts

This PR changes the `Insufficient balance in the wallet` error message to be more descriptive by showing the amount the wallet tried to send, the current balance of the wallet and the negative difference between the two values.
This can aid debugging of third party services and tools, for example when there are issues with voluntary reward sharing scripts run by delegates.

refactor(core-transactions): more descriptive error when balance is insufficient

---

install.sh
packages/core-blockchain/src/state-machine/actions/index.ts
packages/core-blockchain/src/state-machine/actions/initialize.ts
packages/core-blockchain/src/state-machine/machine.ts
packages/core-kernel/src/contracts/state/index.ts
packages/core-kernel/src/contracts/state/state-loader.ts
packages/core-kernel/src/contracts/state/state-saver.ts
packages/core-kernel/src/contracts/state/wallets.ts
packages/core-kernel/src/ioc/identifiers.ts
packages/core-state/package.json
packages/core-state/src/defaults.ts
packages/core-state/src/enums.ts
packages/core-state/src/errors.ts
packages/core-state/src/index.ts
packages/core-state/src/service-provider.ts
packages/core-state/src/state-loader.ts
packages/core-state/src/state-saver.ts
packages/core-state/src/wallets/wallet.ts
packages/core/src/commands/state-purge.ts
packages/crypto/src/utils/byte-buffer-array.ts
packages/crypto/src/utils/index.ts

This PR directly implements loading and saving of the wallet state to disk so that it is not necessary to generate state on every boot, significantly reducing Core's startup time. Essentially, this directly implements a modified and bug fixed version of [Rocket Boot](https://marketsquare.io/projects/rocket-boot) in Core.
This was necessary because our Core code continues to diverge from upstream so our changes would result in the need to continually update the plugin while juggling to make sure it remained compatible with upstream's Core too. Therefore the decision was made to bring a modified version of the plugin directly inside Solar Core, while leaving the plain vanilla version as a plugin for use with upstream Core and its less modified derivatives.
The modifications in this …

feat: load and save state to disk

---

packages/core-api/package.json
packages/core-api/src/www/api.json
packages/core-blockchain/package.json
packages/core-cli/package.json
packages/core-database/package.json
packages/core-forger/package.json
packages/core-kernel/package.json
packages/core-logger-pino/package.json
packages/core-p2p/package.json
packages/core-snapshots/package.json
packages/core-state/package.json
packages/core-transaction-pool/package.json
packages/core-transactions/package.json
packages/core-webhooks/package.json
packages/core/package.json
packages/crypto/package.json
packages/crypto/src/validation/schemas.ts
packages/utils/package.json

This PR releases Solar Core 3.3.1 for mainnet.
Changes since 3.3.0:
\- tighter crypto schema validation

release: mainnet 3.3.1

---

packages/core-blockchain/src/state-machine/actions/check-later.ts
packages/core-forger/src/client.ts
packages/core-kernel/src/contracts/p2p/network-monitor.ts
packages/core-kernel/src/contracts/p2p/peer-communicator.ts
packages/core-kernel/src/contracts/p2p/server.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/schemas.ts
packages/core-p2p/src/socket-server/codecs/internal.ts
packages/core-p2p/src/socket-server/codecs/proto/protos.d.ts
packages/core-p2p/src/socket-server/codecs/proto/protos.js
packages/core-p2p/src/socket-server/codecs/proto/transactions.proto
packages/core-p2p/src/socket-server/codecs/transactions.ts
packages/core-p2p/src/socket-server/controllers/internal.ts
packages/core-p2p/src/socket-server/controllers/transactions.ts
packages/core-p2p/src/socket-server/routes/internal.ts
packages/core-p2p/src/socket-server/routes/transactions.ts
packages/core-p2p/src/transaction-broadcaster.ts
packages/core-p2p/src/utils/build-rate-limiter.ts
packages/core-transaction-pool/package.json
packages/core-transaction-pool/src/errors.ts
packages/core-transaction-pool/src/processor.ts

Our security goal for forging delegate nodes is for them to eventually fully operate behind a firewall with their p2p port closed. Although we're not there yet, this PR brings us one step closer to achieving it by polling the network for unconfirmed transactions and downloading them from other peers that receive them via their `postTransactions` endpoint or api. This is accomplished by opening up the existing `getUnconfirmedTransactions` endpoint by moving it from the `internal` route to the public `transactions` route and defining an appropriate protobuf codec and rate limit.
It also fixes some issues with the transaction broadcaster which could lead to validation errors causing a sudden loss of all peers.

feat: poll for unconfirmed transactions

---

packages/core-api/src/resources/transaction-with-block.ts
packages/core-api/src/resources/transaction.ts
packages/core-database/src/migrations/20220615100000-null-recipient-ids-in-transactions-table.ts
packages/core-database/src/migrations/20220615200000-null-amounts-in-transactions-table.ts
packages/core-database/src/utils/transform.ts
packages/core-state/src/block-state.ts
packages/core-state/src/state-builder.ts
packages/core-transactions/src/handlers/transaction.ts
packages/crypto/src/blocks/block.ts
packages/crypto/src/blocks/factory.ts
packages/crypto/src/transactions/builders/transactions/core/delegate-registration.ts
packages/crypto/src/transactions/builders/transactions/core/delegate-resignation.ts
packages/crypto/src/transactions/builders/transactions/core/htlc-claim.ts
packages/crypto/src/transactions/builders/transactions/core/htlc-lock.ts
packages/crypto/src/transactions/builders/transactions/core/htlc-refund.ts
packages/crypto/src/transactions/builders/transactions/core/ipfs.ts
packages/crypto/src/transactions/builders/transactions/core/multi-payment.ts
packages/crypto/src/transactions/builders/transactions/core/multi-signature.ts
packages/crypto/src/transactions/builders/transactions/core/second-signature.ts
packages/crypto/src/transactions/builders/transactions/core/transfer.ts
packages/crypto/src/transactions/builders/transactions/core/vote.ts
packages/crypto/src/transactions/builders/transactions/solar/vote.ts
packages/crypto/src/transactions/builders/transactions/transaction.ts
packages/crypto/src/transactions/deserialiser.ts
packages/crypto/src/transactions/factory.ts
packages/crypto/src/transactions/types/core/multi-payment.ts
packages/crypto/src/transactions/types/schemas.ts

Currently, every transaction stores a `recipientId` and `amount` value even when they are not needed. In such cases, the `amount` is 0 and the `recipientId` is the address of the sender. This takes up disk space and memory and would only get worse with time, so this PR removes irrelevant `recipientId` and `amount` properties from transactions that do not require them, and nullifies them in the database which reduces the memory footprint.
That is to say, in the case of `recipientId`, only types 0 and 8 from typegroup 1 now store the `recipientId` since no other transaction types use it, and in the case of `amount`, only types 0 and 8 from typegroup 1 and type 0 from typegroup 2 will store the value.

refactor: remove irrelevant transaction properties

---

packages/core-blockchain/src/blockchain.ts
packages/core-blockchain/src/process-blocks-job.ts
packages/core-blockchain/src/state-machine/actions/download-blocks.ts
packages/core-blockchain/src/state-machine/actions/start-fork-recovery.ts
packages/core-kernel/src/contracts/blockchain/blockchain.ts
packages/core-kernel/src/contracts/p2p/network-monitor.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/peer-processor.ts

This PR enhances our fork recovery system to automatically detect a fork when we are on the minority chain as soon as it happens. This is possible because we regularly scan the network for blocks and we only include delegates in consensus decisions, so as soon as a block cannot be chained, we poll all the delegate nodes to check if we are on a fork.
If 50%+1 delegates confirm that we are on a fork, recovery starts immediately and the forked block is downloaded from the node that triggered the recovery algorithm, thus removing the roulette of potentially redownloading a bad block from the wrong fork over and over again, and the node should be back on the majority chain within 30 seconds or so from the moment it is detected.

refactor: nearly instantaneous fork recovery

---

packages/core-api/src/resources-new/delegate.ts
packages/core-api/src/services/delegate-search-service.ts
packages/core-api/src/services/wallet-search-service.ts
packages/core-api/src/www/api.json
packages/core-transactions/src/errors.ts
packages/core-transactions/src/handlers/core/delegate-registration.ts
packages/core-transactions/src/handlers/core/delegate-resignation.ts
packages/crypto/src/enums.ts
packages/crypto/src/transactions/builders/transactions/core/delegate-resignation.ts
packages/crypto/src/transactions/types/core/delegate-resignation.ts
packages/crypto/src/transactions/types/schemas.ts

This PR adds a `resignationType` asset to the existing delegate resignation transaction type to specify whether the resignation is temporary (0 or omitted; default), permanent (1) or being revoked (2).
Where no asset has been specified, it will default to temporary, which means - by intentional design - all existing resignations that occurred prior to the implementation of this PR will automatically become temporary, ergo potentially revocable. Delegates wishing to make them permanent can resubmit a (free) resignation transaction with the `resignationType` asset set to 1.
As the name suggests, only temporary resignations may be revoked, and revocation can only occur after a fixed period of blocks have been produced since the resignation transaction was sent. This is to reduce the …

feat: temporary and permanent delegate resignation

---

packages/blockchain/src/processor/block-processor.ts
packages/state/src/wallets/indexers/indexers.ts
packages/transactions/src/handlers/transaction.ts
plugins/sxp-swap/src/sxp-swap.ts

This adds extra guards to prevent empty wallets being added to the wallet repository going forward by re-indexing any wallet involved in a transaction after attempting to apply or revert it. It also prevents any non-empty wallets that become empty after reverting a transaction from lingering in the wallet repository.

fix: prevent adding empty wallets to repository

---

packages/kernel/src/enums/events.ts
packages/transactions/src/handlers/core/vote.ts
packages/transactions/src/handlers/solar/vote.ts

This enhances the `wallet.vote` event to also include details of the previous vote from the wallet so that delegates can use it to track whenever a wallet starts voting for them, cancels their vote for them or revises their vote allocation for them.

feat(transactions): emit event when delegate vote state changes

---

packages/crypto/package.json
packages/crypto/src/crypto/hdwallet.ts
pnpm-lock.yaml

Unfortunately the `bip32` package used in the `HDWallet` crypto class is not compatible with Node.js 17 onwards (https://github.com/bitcoinjs/bip32/issues/59) and since we now use Node.js 18 in production, this was a breaking change for us. With no fix in sight, we have switched from that package to `@scure/bip32` instead.
Also, it seems like the upstream implementation of the `HDWallet` crypto class is overly complicated for our needs, so it was pared down as part of this PR.

refactor(crypto): use bip32 implementation compatible with node v17+

---

packages/kernel/src/contracts/state/wallets.ts
packages/state/src/state-loader.ts
packages/state/src/state-saver.ts
packages/state/src/wallets/wallet.ts
packages/transactions/src/handlers/core/delegate-registration.ts
packages/transactions/src/handlers/core/delegate-resignation.ts
packages/transactions/src/handlers/core/vote.ts
packages/transactions/src/handlers/solar/vote.ts

This PR refactors Core to no longer require the generic state history concept, instead making use of the already existing transaction history service. This means that Core no longer has to store the entire history of certain wallet attributes in memory all the time.
This has resulted in an immediate 85% reduction in the size of our disk-stored saved state files based on the current state of mainnet at the time of writing.

refactor: use transaction history service instead of generic state history

---

packages/api/src/controllers/delegates.ts
packages/api/src/event-listener.ts
packages/api/src/resources/block-with-transactions.ts
packages/api/src/schemas.ts
packages/api/src/www/api.json
packages/blockchain/src/blockchain.ts
packages/blockchain/src/processor/block-processor.ts
packages/blockchain/src/processor/handlers/unchained-handler.ts
packages/blockchain/src/state-machine/actions/check-later.ts
packages/crypto/src/blocks/block.ts
packages/crypto/src/blocks/factory.ts
packages/crypto/src/interfaces/block.ts
packages/database/src/block-filter.ts
packages/database/src/migrations/20220813000000-add-username-to-blocks-table.ts
packages/database/src/model-converter.ts
packages/database/src/models/block.ts
packages/database/src/repositories/block-repository.ts
packages/database/src/repositories/transaction-repository.ts
packages/kernel/src/contracts/blockchain/blockchain.ts
packages/kernel/src/contracts/database/models.ts
packages/kernel/src/contracts/shared/block-history-service.ts
packages/p2p/src/network-state.ts
packages/p2p/src/peer-verifier.ts
packages/p2p/src/socket-server/controllers/blocks.ts
packages/p2p/src/socket-server/controllers/internal.ts
packages/snapshots/src/codecs/message-pack-codec.ts
packages/state/src/block-state.ts
packages/state/src/round-state.ts
packages/state/src/state-builder.ts
packages/transactions/src/handlers/core/delegate-registration.ts

This PR lays the foundations for a new flexible format for blocks on the Solar blockchain. It adds a new column to the `blocks` database table containing the name of the delegate that produced the block and changes most internal delegate wallet lookups to use the delegate's username rather than its public key. It also adds support for searching and sorting by `username` in the `/blocks` API endpoint.
**Important note:** This will trigger a database migration that will take several minutes to complete.

refactor: use delegate username instead of generator public key

---

packages/crypto/package.json
packages/crypto/src/blocks/factory.ts
packages/crypto/src/crypto/hash.ts
packages/crypto/src/crypto/hdwallet.ts
packages/crypto/src/crypto/message.ts
packages/crypto/src/identities/keys.ts
packages/crypto/src/identities/public-key.ts
packages/crypto/src/interfaces/identities.ts
packages/crypto/src/transactions/builders/transactions/core/second-signature.ts
packages/crypto/src/transactions/builders/transactions/transaction.ts
packages/forger/src/delegate.ts
packages/p2p/src/network-monitor.ts
packages/p2p/src/socket-server/controllers/peer.ts
pnpm-lock.yaml

BLS12-381 has been on our radar for a while as the signature candidate for Solar's new block format which is finally being implemented, so this PR adds the necessary support for generating such key pairs, as well as signing and verifying messages and aggregating public keys and signatures.

feat(crypto): implement bls12-381

---

packages/transactions/src/handlers/core/vote.ts
packages/transactions/src/handlers/solar/vote.ts

The upstream implementation prohibits voting for a resigned delegate. In their context, it totally makes sense - resignations are always permanent and you can only vote for one delegate per wallet, so it is logical to prohibit voting for resigned delegates.
Here, though, the argument is less convincing. Resignations may be temporary, and a wallet may be voting for multiple delegates. It makes little sense to demand, on the protocol level, that a voter of multiple delegates must remove all their existing votes for a resigned delegate before being able to adjust their allocated vote weight for other completely unrelated delegates from the same wallet. The argument is also strong for allowing voting for temporarily resigned delegates so that they have enough votes to re-enter the top 53 …

refactor(transactions): allow voting for resigned delegates

---

packages/api/src/controllers/blockchain.ts
packages/api/src/resources-new/wallet.ts
packages/api/src/routes/blockchain.ts
packages/api/src/services/wallet-search-service.ts
packages/crypto/src/networks/mainnet/network.json
packages/crypto/src/networks/testnet/network.json
packages/database/src/block-filter.ts
packages/database/src/block-history-service.ts
packages/database/src/migrations/20220831000000-add-id-index-with-operator-class-to-blocks-table.ts
packages/database/src/migrations/20220831100000-add-id-index-with-operator-class-to-transactions-table.ts
packages/database/src/transaction-filter.ts
packages/database/src/transaction-history-service.ts
packages/kernel/src/contracts/shared/block-history-service.ts
packages/kernel/src/contracts/shared/transaction-history-service.ts

This adds a new (ws)api endpoint `/blockchain/search/{id}` to search the blockchain, where `{id}` can be a (partial) address, block id, delegate name, public key or transaction id.

feat: search the blockchain

---

packages/api/src/resources-new/delegate.ts
packages/api/src/resources/block-with-transactions.ts
packages/api/src/services/delegate-search-service.ts
packages/api/src/www/api.json
packages/crypto/src/blocks/block.ts
packages/crypto/src/interfaces/block.ts
packages/crypto/src/interfaces/donation.ts
packages/crypto/src/interfaces/index.ts
packages/crypto/src/networks/mainnet/milestones.json
packages/crypto/src/networks/testnet/milestones.json
packages/crypto/src/utils/index.ts
packages/database/src/migrations/20220902000000-rename-dev_fund-to-donations-in-blocks-table.ts
packages/database/src/models/block.ts
packages/database/src/repositories/block-repository.ts
packages/kernel/src/contracts/database/models.ts
packages/kernel/src/contracts/state/wallets.ts
packages/snapshots/src/codecs/message-pack-codec.ts
packages/state/src/block-state.ts
packages/state/src/state-builder.ts
packages/transactions/src/handlers/core/delegate-registration.ts

This PR renames `devFund` to `donations` to better reflect its nature as a generic platform for allocating donations from block rewards.

refactor: block reward donations

---

packages/kernel/src/contracts/pool/sender-mempool.ts
packages/kernel/src/contracts/pool/sender-state.ts
packages/kernel/src/contracts/pool/service.ts
packages/pool/src/mempool.ts
packages/pool/src/sender-mempool.ts
packages/pool/src/sender-state.ts
packages/pool/src/service.ts
packages/transactions/src/handlers/transaction.ts

This adds a public `getPoolWallet` method to the pool service which takes an address and returns a matching wallet from the pool if it exists. Unlike the blockchain wallet repository, this wallet takes into account the balance and nonce including any unconfirmed transactions in the pool, so it can be used by plugins to ensure that a wallet has a sufficient balance for a new transaction and to deduce the correct nonce to use when also considering any existing unconfirmed transactions in the pool for that wallet too for that specific node.
An example use case could be for a plugin that creates multiple transactions from the same wallet and adds them to the pool to be processed at the same time, without having to keep a local counter for the nonce and available balance, which may get out of …

refactor(pool): add method to get pool wallet

---

packages/crypto/src/blocks/block.ts
packages/crypto/src/blocks/factory.ts
packages/crypto/src/interfaces/transactions.ts
packages/crypto/src/transactions/deserialiser.ts
packages/crypto/src/transactions/factory.ts
packages/crypto/src/transactions/types/core/htlc-lock.ts
packages/crypto/src/transactions/types/core/legacy-transfer.ts
packages/crypto/src/transactions/types/core/transfer.ts
packages/crypto/src/transactions/types/transaction.ts
packages/kernel/src/contracts/pool/storage.ts
packages/kernel/src/contracts/pool/worker.ts
packages/kernel/src/contracts/state/transaction-validator.ts
packages/pool/src/collator.ts
packages/pool/src/defaults.ts
packages/pool/src/errors.ts
packages/pool/src/mempool.ts
packages/pool/src/processor.ts
packages/pool/src/sender-state.ts
packages/pool/src/service-provider.ts
packages/pool/src/service.ts
packages/pool/src/storage.ts
packages/pool/src/worker-pool.ts
packages/pool/src/worker-script-handler.ts
packages/pool/src/worker-script.ts
packages/pool/src/worker.ts
packages/state/src/transaction-validator.ts
plugins/sxp-swap/src/sxp-swap.ts

This PR includes several optimisations to try to make transaction handling more efficient, especially in the context of the pool. Some redundant upstream code was removed, such as future timestamp checking since we do not have the legacy baggage of their original transaction version that included timestamps, and we ensure that all incoming transactions are handled by workers.
The main performance pain point is the way that addresses are encoded from the 21-byte buffer to the base58 address string during transaction deserialisation. This is a relatively slow process and there are cases where a full pool consisting of multi-recipient transfers with 100 addresses could take in excess of 6 seconds to process. If this coincided with a milestone change, all transactions in the full pool would …

refactor: performance optimisations

---

packages/api/package.json
packages/blockchain/package.json
packages/blockchain/src/blockchain.ts
packages/cli/package.json
packages/core/package.json
packages/crypto/package.json
packages/database/package.json
packages/forger/package.json
packages/kernel/package.json
packages/kernel/src/contracts/pool/service.ts
packages/logger/package.json
packages/nes/package.json
packages/p2p/package.json
packages/pool/package.json
packages/pool/src/service.ts
packages/snapshots/package.json
packages/state/package.json
packages/transactions/package.json
packages/webhooks/package.json

This PR releases Solar Core 4.1.3 for mainnet.
Changes since 4.1.2:
\- listen to queue drain event for the block processing queue only rather than the global `QueueEvent.Finished` event

release: mainnet 4.1.3

---

README.md
packages/api/src/server.ts
packages/core/src/commands/config-forger-bip39.ts
packages/core/src/commands/config-forger.ts
packages/core/src/commands/core-run.ts
packages/core/src/commands/core-start.ts
packages/core/src/commands/forger-run.ts
packages/core/src/commands/forger-start.ts
packages/core/src/internal/crypto.ts
packages/crypto/src/crypto/hdwallet.ts
packages/crypto/src/crypto/message.ts
packages/crypto/src/identities/address.ts
packages/crypto/src/identities/keys.ts
packages/crypto/src/identities/private-key.ts
packages/crypto/src/identities/public-key.ts
packages/crypto/src/identities/wif.ts
packages/crypto/src/transactions/builders/transactions/core/extra-signature.ts
packages/crypto/src/transactions/builders/transactions/transaction.ts
packages/kernel/src/services/config/drivers/local.ts

Until now, Core has referred to seed phrases as "passphrases", since that is how upstream does it. This PR changes that to use the more industry standard "mnemonic" term instead, since "passphrase" has a different meaning in the wider crypto space.

refactor: rename passphrase to mnemonic

---

packages/blockchain/src/blockchain.ts
packages/blockchain/src/state-machine/actions/start-fork-recovery.ts
packages/cli/package.json
packages/cli/src/action-factory.ts
packages/cli/src/actions/log-process.ts
packages/core/src/commands/all-log.ts
packages/core/src/commands/core-log.ts
packages/core/src/commands/forger-log.ts
packages/core/src/commands/relay-log.ts
packages/database/src/repositories/block-repository.ts
packages/database/src/service-provider.ts
packages/forger/src/forger-service.ts
packages/kernel/package.json
packages/kernel/src/contracts/kernel/log.ts
packages/kernel/src/services/log/enums.ts
packages/kernel/src/services/queue/drivers/memory.ts
packages/kernel/src/utils/index.ts
packages/kernel/src/utils/log-colour.ts
packages/logger/package.json
packages/logger/src/defaults.ts
packages/logger/src/driver.ts
packages/logger/src/service-provider.ts
packages/p2p/src/network-monitor.ts
packages/snapshots/package.json
packages/snapshots/src/database-service.ts
packages/snapshots/src/progress-renderer.ts
packages/snapshots/src/snapshot-service.ts
pnpm-lock.yaml

This PR optimises the performance of logging and cleans up some incorrect emoji and log levels.
During a sync from zero, or any operation with a lot of logging in a short period of time, the synchronous logger was causing a bottleneck. This has been revised now to be much more efficient by using a worker thread, with significantly faster sync from zero speeds as a result.
Additionally, output is no longer logged to stdout/stderr, so that means there are no more logs stored in `~/.pm2/logs` so the only saved logs are the NDJSON files in `~/.local/state/solar-core/{devnet|mainnet|testnet}`, and again this is for performance reasons. However, by using the `solar log:{all|core|forger|relay}` command, you can still see the logs in the prettified format as this command now parses the NDJSON …

refactor: logging performance and cleanup

---

packages/crypto/src/crypto/hash.ts

This PR combines the multiple signing and verifying methods for the different types of Schnorr signatures into just one signing function (`signSchnorr`) and one verifying function (`verifySchnorr`).

refactor(crypto): merge schnorr hash methods

---

packages/crypto/src/networks/mainnet/milestones.json
plugins/sxp-swap/src/defaults.ts
plugins/sxp-swap/src/errors.ts
plugins/sxp-swap/src/sxp-swap.ts

This PR modifies the `sxp-swap` plugin in the following ways:
1. The nodes used for ETH and BSC cross-chain verification have been changed to be under the solar.org domain.
2. All swaps before height 2,750,000 do not require cross-chain verification anymore as they are already well confirmed, which speeds up sync.
3. The swap wallet can now register a second signature with a pre-defined public key.

refactor: no cross-chain check for old swaps and add second signature to swap wallet

---

packages/api/package.json
packages/blockchain/package.json
packages/cli/package.json
packages/core/package.json
packages/crypto/package.json
packages/crypto/src/networks/mainnet/milestones.json
packages/database/package.json
packages/forger/package.json
packages/kernel/package.json
packages/logger/package.json
packages/nes/package.json
packages/p2p/package.json
packages/pool/package.json
packages/snapshots/package.json
packages/state/package.json
packages/transactions/package.json
packages/webhooks/package.json
plugins/sxp-swap/src/defaults.ts
plugins/sxp-swap/src/errors.ts
plugins/sxp-swap/src/sxp-swap.ts

This PR releases Solar Core 4.2.0 for mainnet.
Changes since 4.1.3:
\- performance and security improvements for the `sxp-swap` plugin

release: mainnet 4.2.0

---

packages/api/src/services/delegate-search-service.ts
packages/blockchain/src/state-machine/actions/syncing-complete.ts
packages/kernel/src/contracts/p2p/network-monitor.ts
packages/kernel/src/contracts/p2p/peer.ts
packages/p2p/src/network-monitor.ts
packages/p2p/src/network-state.ts
packages/p2p/src/peer-communicator.ts
packages/p2p/src/peer.ts
packages/p2p/src/socket-server/controllers/peer.ts
packages/state/src/round-state.ts
packages/transactions/src/handlers/solar/vote.ts

This PR prevents votes for offline block producers being accepted in the pool. Each voted block producer is checked against the node's peer list to ensure it is signalling that it is online with a valid `version`. If no `version` is present, the block producer is considered to be offline and the vote transaction is rejected in the pool.
The `version` is updated every round and removed if it is more than 5 rounds old.
This also means that all block producers now signal a `version` if they are online, rather than the previous behaviour where only the active top 53 block producers did so.

feat: only allow votes in pool for block producers running nodes
